### ISSUE TITLE
table of contents fix

### ISSUE THREAD

**Issue by xsolvia** [greysoh/blog-gen#1]
don't have push access and i don't feel like forking for literally 1 line of code so

`line 60 of index.js:`

```diff
- if (j.endsWith(".md")) {
+ if (j.endsWith(".md") && !j.endsWith("toc.md")) {
```

pretty sure you don't want the Table of Contents to show up in the Table of Contents.

**Comment by xsolvia** [comment]
when looking at a blog, and clicking on a topic, i (and other people) would usually expect just a list of the actual blog posts in that topic

**Comment by lunrsh** [comment]
looks good
